"""Add sub_category and currency to Expense model.

Revision ID: 687b4fe2df8c
Revises: 5cd02132fce8
Create Date: 2025-05-01 17:55:21.647367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687b4fe2df8c'
down_revision = '5cd02132fce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))
        batch_op.create_index(batch_op.f('ix_expense_sub_category'), ['sub_category'], unique=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_index(batch_op.f('ix_expense_sub_category'))
        batch_op.drop_column('currency')
        batch_op.drop_column('sub_category')

    # ### end Alembic commands ###
