"""Add SharedExpense model

Revision ID: aba83c0701c6
Revises: 687b4fe2df8c
Create Date: 2025-05-12 18:23:43.971348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba83c0701c6'
down_revision = '687b4fe2df8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_by_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('categories', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_expense')
    # ### end Alembic commands ###
