"""Remove data_type and categories from SharedExpense

Revision ID: c8dd68d96f8f
Revises: aba83c0701c6
Create Date: 2025-05-13 16:22:26.678956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8dd68d96f8f'
down_revision = 'aba83c0701c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_expense', schema=None) as batch_op:
        batch_op.drop_column('data_type')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('data_type', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
